#if os(macOS)
import Foundation
import HTTPTypes
import Testing
@testable import Transit

/// Regression tests for the MCP Streamable HTTP endpoint routes.
///
/// MCP 2025-03-26 permits GET to open an SSE listening stream when the client
/// accepts `text/event-stream`. A GET without that required negotiation remains
/// unsupported, while POST dispatch, origin validation, and unrelated routes
/// keep their existing behavior.
@MainActor @Suite(.serialized)
struct MCPServerRouteTests {

    @Test func getMcpWithoutEventStreamAcceptReturnsMethodNotAllowed() async throws {
        let env = try MCPTestHelpers.makeEnv()
        let response = try await respond(
            handler: env.handler,
            method: .get,
            path: "/mcp"
        )

        #expect(response.status == .methodNotAllowed)
        #expect(response.allow == "POST")
    }

    @Test func eventStreamAcceptParsingRequiresExactPositiveQualityMediaRange() {
        #expect(MCPServer.acceptsEventStream("text/event-stream"))
        #expect(MCPServer.acceptsEventStream(
            "application/json, TEXT/EVENT-STREAM; charset=utf-8; q=0.5"
        ))
        #expect(MCPServer.acceptsEventStream(
            "text/event-stream;q=0, text/event-stream;q=0.001"
        ))

        #expect(!MCPServer.acceptsEventStream(nil))
        #expect(!MCPServer.acceptsEventStream("application/x-text/event-stream"))
        #expect(!MCPServer.acceptsEventStream("text/event-streaming"))
        #expect(!MCPServer.acceptsEventStream("text/event-stream;q=0"))
        #expect(!MCPServer.acceptsEventStream("text/event-stream;q=1.1"))
        #expect(!MCPServer.acceptsEventStream("text/event-stream;q=.5"))
        #expect(!MCPServer.acceptsEventStream("text/event-stream;note=\"a,b\";q=0"))
    }

    @Test func getMcpRejectsEventStreamWithZeroQuality() async throws {
        let env = try MCPTestHelpers.makeEnv()
        let response = try await respond(
            handler: env.handler,
            method: .get,
            path: "/mcp",
            accept: "application/json, text/event-stream;q=0"
        )

        #expect(response.status == .methodNotAllowed)
        #expect(response.allow == "POST")
    }

    @Test func getMcpRejectsEventStreamMediaTypeSuperstring() async throws {
        let env = try MCPTestHelpers.makeEnv()
        let response = try await respond(
            handler: env.handler,
            method: .get,
            path: "/mcp",
            accept: "application/x-text/event-stream"
        )

        #expect(response.status == .methodNotAllowed)
        #expect(response.allow == "POST")
    }

    @Test func getMcpWithEventStreamAcceptRequiresSession() async throws {
        let env = try MCPTestHelpers.makeEnv()
        let response = try await respond(
            handler: env.handler,
            method: .get,
            path: "/mcp",
            accept: "text/event-stream; charset=utf-8; q=0.5"
        )

        #expect(response.status == .badRequest)
    }

    @Test func getMcpRejectsUnknownSession() async throws {
        let env = try MCPTestHelpers.makeEnv()
        let response = try await respond(
            handler: env.handler,
            method: .get,
            path: "/mcp",
            accept: "text/event-stream",
            sessionID: "unknown-session"
        )

        #expect(response.status == .notFound)
    }

    @Test func postMcpStillDispatchesNormally() async throws {
        let env = try MCPTestHelpers.makeEnv()
        let response = try await respond(
            handler: env.handler,
            method: .post,
            path: "/mcp",
            body: #"{"jsonrpc":"2.0","id":1,"method":"ping"}"#
        )

        #expect(response.status == .ok)
    }

    @Test func getMcpStillValidatesUntrustedOrigins() async throws {
        let env = try MCPTestHelpers.makeEnv()
        let response = try await respond(
            handler: env.handler,
            method: .get,
            path: "/mcp",
            origin: "https://evil.example.com"
        )

        #expect(response.status == .forbidden)
    }

    @Test func getMcpStillValidatesNonLoopbackHost() async throws {
        let env = try MCPTestHelpers.makeEnv()
        let response = try await respond(
            handler: env.handler,
            method: .get,
            path: "/mcp",
            host: "rebind.example.com:3141"
        )

        #expect(response.status == .forbidden)
    }

    @Test func headMcpRemainsNotFoundWithoutAutoGeneratedHeadRoute() async throws {
        let env = try MCPTestHelpers.makeEnv()
        let response = try await respond(
            handler: env.handler,
            method: .head,
            path: "/mcp"
        )

        #expect(response.status == .notFound)
        #expect(response.allow == nil)
    }

    @Test func optionsMcpRemainsNotFoundWithoutExplicitOptionsRoute() async throws {
        let env = try MCPTestHelpers.makeEnv()
        let response = try await respond(
            handler: env.handler,
            method: .options,
            path: "/mcp"
        )

        #expect(response.status == .notFound)
        #expect(response.allow == nil)
    }

    @Test func getOnUnrelatedPathRemainsNotFound() async throws {
        let env = try MCPTestHelpers.makeEnv()
        let response = try await respond(
            handler: env.handler,
            method: .get,
            path: "/not-mcp"
        )

        #expect(response.status == .notFound)
        #expect(response.allow == nil)
    }

    private func respond(
        handler: MCPToolHandler,
        method: HTTPRequest.Method,
        path: String,
        origin: String? = nil,
        host: String = "127.0.0.1:3141",
        accept: String? = nil,
        sessionID: String? = nil,
        body: String = ""
    ) async throws -> MCPHTTPTestResponse {
        try await MCPTestHelpers.respond(
            handler: handler,
            method: method,
            path: path,
            origin: origin,
            authority: host,
            accept: accept,
            sessionID: sessionID,
            body: body,
            loggerLabel: "mcp-route-tests"
        )
    }
}

#endif
