# SwiftLint Configuration for Transit

# Paths to include/exclude
included:
  - Transit/Transit
  - Transit/TransitTests
  - Transit/TransitUITests

excluded:
  - Transit/Transit/Assets.xcassets
  - DerivedData
  - .build

# Opt-in rules
opt_in_rules:
  - explicit_init
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - multiline_arguments
  - multiline_parameters
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Disabled rules
disabled_rules:
  - todo # Allow TODO comments during development

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 800

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
  excluded:
    - id
    - tc # test case variable in table-driven tests

type_name:
  min_length: 3
  max_length: 50

# Custom rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: "\\bprint\\("
    message: "Use proper logging instead of print()"
    severity: warning
